spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/callwork}
    username: ${DB_USER:callwork}
    password: ${DB_PASSWORD:callwork}
    driver-class-name: org.postgresql.Driver
